### ISSUE TITLE
Fatal Error Occurring

### ISSUE THREAD

**Issue by doreym** [matthiasmullie/path-converter#11]
Fatal error: Cannot declare interface MatthiasMullie\PathConverter\ConverterInterface, because the name is already in use in /homepages/42/d831472013/htdocs/clickandbuilds/OsmoUk/wp-content/plugins/custom-css-js-pro/includes/vendor/path-converter/src/ConverterInterface.php on line 14

Just updating some css code and this popped up after saving. I cannot amend or change anything without this message.

Thanks

**Comment by matthiasmullie** [comment]
Hi,

I'm afraid there's not much that I can do to help here. You're simply including the same file (or a duplicate thereof) more than once, which is causing the error. I.e., the issue is not with this project, but in how it's used.

Judging from your error message, it looks like you're using https://www.silkypress.com/simple-custom-css-js-pro/, which is in turn using this project. I'd suggest getting in touch with them. I don't know whether they'll be able to help, but at least they're one step closer to the actual problem.

Best of luck.
